### ISSUE TITLE
vscode and Bastion WALLIX

### ISSUE THREAD

**Issue by Pit4Coding** [Pit4Coding/vscoding#1]
VSCode: 1.88.1
Plateform: Ubuntu 20.04
Bastion: 9.0.7
target: Redhat 9

I'm trying to access via SSH to my redhat from vscode hosted on ubuntu, through a Bastion WALLIX. To do that I have installed extension Remote-SSH and made a host configuration as this:

Host MyRedhat
     Hostname "\<fqdn Bastion\>"
     User "Interactive\@\<Device\>:SSH:\<group\>:\<login to Bastion\>"

I am prompted (credential) for access to the bastion but after I get errors for connection at the secondary target.

Here are the logs:

[08:13:38.964] Log Level: 2
[08:13:39.034] SSH Resolver called for "ssh-remote+infrarh9.vertou.org", attempt 1
[08:13:39.034] "remote.SSH.useLocalServer": true
[08:13:39.037] "remote.SSH.useExecServer": true
[08:13:39.037] "remote.SSH.path": undefined
[08:13:39.037] "remote.SSH.configFile": /tmp/maconfig
[08:13:39.038] "remote.SSH.useFlock": true
[08:13:39.038] "remote.SSH.lockfilesInTmp": false
[08:13:39.038] "remote.SSH.localServerDownload": auto
[08:13:39.038] "remote.SSH.remoteServerListenOnSocket": false
[08:13:39.038] "remote.SSH.showLoginTerminal": true
[08:13:39.038] "remote.SSH.defaultExtensions": []
[08:13:39.038] "remote.SSH.loglevel": 2
[08:13:39.038] "remote.SSH.enableDynamicForwarding": true
[08:13:39.042] "remote.SSH.enableRemoteCommand": false
[08:13:39.042] "remote.SSH.serverPickPortsFromRange": {}
[08:13:39.042] "remote.SSH.serverInstallPath": {}
[08:13:39.058] VS Code version: 1.88.1
[08:13:39.058] Remote-SSH version: remote-ssh@0.110.1
[08:13:39.058] linux x64
[08:13:39.067] SSH Resolver called for host: infrarh9.vertou.org
[08:13:39.067] Setting up SSH remote "infrarh9.vertou.org"
[08:13:39.095] Acquiring local install lock: /tmp/vscode-remote-ssh-7cbd370f-install.lock
[08:13:39.108] Looking for existing server data file at /home/pierre/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-7cbd370f-e170252f762678dec6ca2cc69aba1570769a5d39-0.110.1-es/data.json
[08:13:39.110] Using commit id "e170252f762678dec6ca2cc69aba1570769a5d39" and quality "stable" for server
[08:13:39.135] Install and start server if needed
[08:13:39.153] PATH: /home/pierre/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/usr/local/go/bin:/usr/local/go/bin:/usr/local/go/bin
[08:13:39.153] Checking ssh with "ssh -V"
[08:13:39.266] > OpenSSH_8.2p1 Ubuntu-4ubuntu0.11, OpenSSL 1.1.1f  31 Mar 2020

[08:13:39.270] Using SSH config file "/tmp/maconfig"
[08:13:39.272] askpass server listening on /run/user/1000/vscode-ssh-askpass-bfe18bffd574c12f6511c13b1417f79d727d300d.sock
[08:13:39.273] Spawning local server with {"serverId":1,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-e86f3d00a2551586c843d73e0ba8a4066a930a8d.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","41007","-o","ConnectTimeout=15","-F","/tmp/maconfig","infrarh9.vertou.org"],"serverDataFolderName":".vscode-server","dataFilePath":"/home/pierre/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-7cbd370f-e170252f762678dec6ca2cc69aba1570769a5d39-0.110.1-es/data.json"}
[08:13:39.273] Local server env: {"SSH_AUTH_SOCK":"/tmp/ssh-glxlUDPSTXWB/agent.59812","SHELL":"/bin/bash","DISPLAY":":0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/pierre/.vscode/extensions/ms-vscode-remote.remote-ssh-0.110.1/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"","VSCODE_SSH_ASKPASS_MAIN":"/home/pierre/.vscode/extensions/ms-vscode-remote.remote-ssh-0.110.1/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-bfe18bffd574c12f6511c13b1417f79d727d300d.sock"}
[08:13:39.296] Spawned 60381
[08:13:39.556] > local-server-1> Running ssh connection command: ssh -v -T -D 41007 -o ConnectTimeout=15 -F /tmp/maconfig infrarh9.vertou.org
[08:13:39.568] > local-server-1> Spawned ssh, pid=60389
[08:13:39.576] stderr> OpenSSH_8.2p1 Ubuntu-4ubuntu0.11, OpenSSL 1.1.1f  31 Mar 2020
[08:13:39.619] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:uPeDK+khjRECvBtCZQwl/C52AWfd/mXRzLiMWza7O7w
[08:13:40.134] Got askpass request: {"request":" WARNING: Access to this system is restricted to duly authorized users only. Any attempt to access this system without authorization or fraudulently remaining within such system will be prosecuted in accordance with the law. Any authorized user is hereby informed and acknowledges that his/her actions may be recorded, retained and audited.\r \r test1@vertou.org's password:"}
[08:13:40.135] Showing password prompt
[08:13:40.144] Listening for interwindow password on /run/user/1000/vscode-ssh-askpass-42945f9178ca517a77dfc244158a97c127e1a549.sock
[08:13:40.144] Writing password prompt to globalState
[08:13:47.951] Got password response
[08:13:47.952] Interactor gave response: *********
[08:13:47.952] Cleaning up other-window auth server
[08:13:48.232] stderr> Authenticated to bastion.vertou.org ([192.168.1.172]:22).
[08:13:48.549] > 
> Account successfully checked out
> 
> Connexion Ã  Interactive@Mon_LAN:SSH...
> Login cible: echo 'ready: b71ea99a2fbd'
> 
> Echec de la connexion Ã  la cible secondaire
> local-server-1> ssh child died, shutting down
[08:13:48.549] stderr> Transferred: sent 2632, received 1756 bytes, in 0.3 seconds
[08:13:48.549] stderr> Bytes per second: sent 8376.2, received 5588.4
[08:13:48.556] Local server exit: 0
[08:13:48.557] Received install output: local-server-1> Running ssh connection command: ssh -v -T -D 41007 -o ConnectTimeout=15 -F /tmp/maconfig infrarh9.vertou.org
local-server-1> Spawned ssh, pid=60389
OpenSSH_8.2p1 Ubuntu-4ubuntu0.11, OpenSSL 1.1.1f  31 Mar 2020
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:uPeDK+khjRECvBtCZQwl/C52AWfd/mXRzLiMWza7O7w
Authenticated to bastion.vertou.org ([192.168.1.172]:22).

Account successfully checked out

Connexion Ã  Interactive@Mon_LAN:SSH...
Login cible: echo 'ready: b71ea99a2fbd'

Echec de la connexion Ã  la cible secondaire
local-server-1> ssh child died, shutting down
Transferred: sent 2632, received 1756 bytes, in 0.3 seconds
Bytes per second: sent 8376.2, received 5588.4

[08:13:48.557] Failed to parse remote port from server output
[08:13:48.563] Resolver error: Error: 
	at g.Create (/home/pierre/.vscode/extensions/ms-vscode-remote.remote-ssh-0.110.1/out/extension.js:2:499181)
	at t.handleInstallOutput (/home/pierre/.vscode/extensions/ms-vscode-remote.remote-ssh-0.110.1/out/extension.js:2:496503)
	at e (/home/pierre/.vscode/extensions/ms-vscode-remote.remote-ssh-0.110.1/out/extension.js:2:557639)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async /home/pierre/.vscode/extensions/ms-vscode-remote.remote-ssh-0.110.1/out/extension.js:2:579548
	at async t.withShowDetailsEvent (/home/pierre/.vscode/extensions/ms-vscode-remote.remote-ssh-0.110.1/out/extension.js:2:583207)
	at async /home/pierre/.vscode/extensions/ms-vscode-remote.remote-ssh-0.110.1/out/extension.js:2:554344
	at async T (/home/pierre/.vscode/extensions/ms-vscode-remote.remote-ssh-0.110.1/out/extension.js:2:552395)
	at async t.resolveWithLocalServer (/home/pierre/.vscode/extensions/ms-vscode-remote.remote-ssh-0.110.1/out/extension.js:2:553884)
	at async k (/home/pierre/.vscode/extensions/ms-vscode-remote.remote-ssh-0.110.1/out/extension.js:2:576765)
	at async t.resolve (/home/pierre/.vscode/extensions/ms-vscode-remote.remote-ssh-0.110.1/out/extension.js:2:580578)
	at async /home/pierre/.vscode/extensions/ms-vscode-remote.remote-ssh-0.110.1/out/extension.js:2:846687
[08:13:48.596] ------

**Comment by Pit4Coding** [comment]
At the end I succeeded to make VsCode to work with Bastion Wallix with SSH.

**Comment by Pit4Coding** [comment]
At the end I succeeded to make VsCode to work with Bastion Wallix with SSH.
